default: &default
  host: localhost
  port: 3306
  user: andreluiz
  password: 230622
  database: orm_mysql

dev:
  <<: *default

prod:
  <<: *default
  port: <%= ENV["MYSQL_PORT"] || "3306" %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>
  user: <%= ENV["MYSQL_USER"] || "andreluiz" %>
  password: <%= ENV["MYSQL_PASS"] || "230622" %>
  database: <%= ENV["MYSQL_PASS"] || "orm_mysql_prod" %>
  